{% set name = "muler" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65803c0b06905c16fce1e7b99246206207b714cd7c6d95a21b3e16f330ee2dde

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - astropy-base >=4.1
    - specutils >=1.5
    - numpy
    - scipy
    - celerite2
    - pandas
    - matplotlib-base
    - importlib_resources
    - h5py

test:
  imports:
    - muler

about:
  home: https://muler.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for working with pipeline-produced data from IGRINS and HPF
  description: |
    muler is an easy to use Python package for post-processing echelle
    spectroscopy from near-infrared astronomical spectrographs.  We currently
    support IGRINS, HPF, and Keck NIRSPEC.
  doc_url: https://muler.readthedocs.io
  dev_url: https://github.com/OttoStruve/muler

extra:
  recipe-maintainers:
    - gully
